### ISSUE TITLE
Identify available APIs for v1 consumption

### ISSUE THREAD

**Issue by TheTedAdams** [TheTedAdams/examined-life#1]
@enriched we need to identify which APIs we will attempt to consume in v1.

From the top of my head:
- MyFitnesPal
- Fitbit

**Comment by enriched** [comment]
From the top of my head:
- google (auth)
- facebook (auth)
- github (auth)

**Comment by TheTedAdams** [comment]
http://mashable.com/2011/11/06/apps-health-productivity/#_

**Comment by TheTedAdams** [comment]
https://dev.fitbit.com/
http://runkeeper.com/developer/healthgraph/
https://developer.foursquare.com/

**Comment by enriched** [comment]
Closed for now, this project is on hold
