### ISSUE TITLE
Identify technical architecture

### ISSUE THREAD

**Issue by TheTedAdams** [TheTedAdams/examined-life#2]
@enriched 
We need to determine what architecture we will use.

Hosted in Windows or Linux? Mostly front end SPA with API backend? Or server rendered templates (ASP.NET, etc.)

**Comment by enriched** [comment]
Scrapers -> Redis DB -> Analytics Engine -> Response

**Comment by enriched** [comment]
Analytics mappings are on a per api basis with dimensions, metrics and segments defined within config file.

**Comment by enriched** [comment]
For general analytics api see https://developers.google.com/analytics/devguides/reporting/core/v3/

**Comment by enriched** [comment]
Close for now, this project is on hold
